### ISSUE TITLE
Schema for Geekbes Mini Smart Socket YM-SW-1

### ISSUE THREAD

**Issue by geert56** [clach04/python-tuya#18]
Here is the schema I retrieved from my dev_data_storage.xml file:
Feel free to include on your wiki.
[
  {
    "mode": "rw",
    "code": "switch_1",
    "name": "单插开关",
    "property": {
      "type": "bool"
    },
    "iconname": "icon-dp_power2",
    "id": 1,
    "type": "obj",
    "desc": ""
  },
  {
    "mode": "rw",
    "code": "countdown",
    "name": "倒计时",
    "property": {
      "unit": "秒",
      "min": 0,
      "max": 86400,
      "scale": 0,
      "step": 1,
      "type": "value"
    },
    "iconname": "icon-dp_time2",
    "id": 11,
    "type": "obj",
    "desc": "可根据产品实际倒计时功能修改。"
  },
  {
    "mode": "rw",
    "code": "randomTime",
    "name": "随机定时",
    "property": {
      "type": "string",
      "maxlen": 255
    },
    "id": 101,
    "type": "obj",
    "desc": "每6个字节代表 #1开关/#2星期/#3#4起始时间(min)/#5#6结束时间(min),最大42组"
  },
  {
    "mode": "rw",
    "code": "cycleTime",
    "name": "循环定时",
    "property": {
      "type": "string",
      "maxlen": 255
    },
    "id": 102,
    "type": "obj",
    "desc": "每10个字节代表 #1开关/#2星期/#3#4起始时间(min)/#5#6结束时间(min)/#7#8开启时间(min)/#9#10关闭时间(min)\\n星期：00(单次)01(周日)02(周一)04(周二)08(周三)10(周四)20(周五)40(周六)"
  },
  {
    "mode": "rw",
    "code": "normalTime",
    "name": "普通定时",
    "property": {
      "type": "string",
      "maxlen": 255
    },
    "id": 103,
    "type": "obj",
    "desc": "每6个字节代表 #1开关/#2星期/#3#4开启时间(min)/#5#6关闭时间(min),最大42组"
  }
]

**Comment by clach04** [comment]
Thanks @geert56 for sharing, added to https://github.com/clach04/python-tuya/wiki/DeviceSchemas - you should be able to edit that wiki page
