### ISSUE TITLE
.status() occasionally restarts device

### ISSUE THREAD

**Issue by glentakahashi** [clach04/python-tuya#37]
I'm seeing some very strange behavior where calling .status() on a wifi socket causes the socket to reset itself (turn off and then on immediately). It doesn't happen every time .status is called, but I can very very regularly see this happen. I've done some digging but haven't been able to diagnose why it's happening yet.

Any ideas as to what's causing this and how to fix it?

**Comment by clach04** [comment]
This is sounds like #29 I've not seen this with my devices. It also sounds like https://github.com/codetheweb/tuyapi/issues/84 which is the Node implementation I'll post comments there.

**Comment by glentakahashi** [comment]
Okay I'll close out in track in the other issues
