### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [clach04/python-tuya#46]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design to improve visualization of your project as my Open Source Contribution?

Thanks for the attention.

**Comment by clach04** [comment]
@anharismail that would be awesome! I don't have any initial ideas or guidelines but if the offer is still good I'd love to see what you had in mind. Maybe attach to this issue?

I understand if you don't have time now as I was slow to respond. Thanks.
