### ISSUE TITLE
PIR & Door/Window Sensor Support?

### ISSUE THREAD

**Issue by codeclinic** [clach04/python-tuya#67]
Does this support the usage of PIR &/or Door/Window Sensors?

**Comment by clach04** [comment]
No - its mostly for polling WiFi devices - I suspect those sensors actively send data rather than being polled (somehow probably via the hubs I've seen online (I got the impression there are some 433Mhz sensors that connect to a hub rather than wifi).

**Comment by BillSobel** [comment]
Sensors send data via Mqtt only.

**Comment by codeclinic** [comment]
> Sensors send data via Mqtt only.

Sensors send data via MQTT? Really? Do you have any info on how we can catch this data?

**Comment by BillSobel** [comment]
Its all documented in the Tuya SDK, but you need actual API keys to login
to MQTT and access the data you cant grab that from the devices..
