### ISSUE TITLE
Update firmware

### ISSUE THREAD

**Issue by blawson327** [clach04/python-tuya#7]
From the cloud API docs, it looks like there is sone firmware updating methods. Any chance we might be able to use that to reflash some of these devices with a different firmware?

I have a geekbes plug that I managed to flash with tasomota using an ftdi connextion, but getting it apart to access the programming pads does a lot of damage to the plug

**Comment by clach04** [comment]
@blawson327 yes remote chance. Interestingly, none of the devices I own needed a firmware update. I do have an unopened device so I'll double check that when I activate it just in case the the firmware update is transparent done. Worth moving this discussion over to https://github.com/codetheweb/tuyapi/issues/5#issuecomment-355752402

Like you, I'd prefer not to have to resort to wiring it up to reflash :)
