### ISSUE TITLE
7.0.6 release

### ISSUE THREAD

**Issue by nicole-ashley** [clach04/python-tuya#71]
Could we please get a new release? The work since `7.0.5` fixes pip installs which I need for my Home Assistant integration, and even updates the version number to `7.0.6`, but there hasn't been a release to PyPI meaning I can't use it.

**Comment by clach04** [comment]
@nikrolls I posted https://github.com/clach04/python-tuya/issues/71 this is 100% **un**tested.

I'm pretty sure HA extension.REQUIREMENTS list is piped through `pip` so assuming the machine has git installed one can use regular git URLs (see https://pip.pypa.io/en/stable/reference/pip_install/#git )which avoids the urgency to publish (especially whilst developing). Something I've NOT tried with pip is using download links like https://github.com/clach04/python-tuya/archive/master.zip

**Comment by nicole-ashley** [comment]
This may work, but currently I'm attempting to have my integration's dependencies preloaded in HA, and based on the HA requirements it needs to come from PyPI. Unless that's different for the wheel repository, @frenck?
